export enum EvaluateFeedbackType {
    STAFF_TO_TEACHER = 'STAFF_TO_TEACHER',
    TEACHER_TO_STAFF = 'TEACHER_TO_STAFF',
    TEACHER_TO_STUDENT = 'TEACHER_TO_STUDENT',
    STUDENT_TO_TEACHER = 'STUDENT_TO_TEACHER',
    STUDENT_TO_STAFF = 'STUDENT_TO_STAFF',
}
