export enum FeedbackEventType {
    PUBLISH_LEARNING_MATERIAL = 'publishLearningMaterialNotification',
    APPROVE_LEARNING_MATERIAL = 'approveLearningMaterialNotification',
    REJECT_LEARNING_MATERIAL = 'rejectLearningMaterialNotification',
    PUBLISH_EXAM = 'publishExamFeedbackNotification',
    APPROVE_EXAM = 'approveExamFeedbackNotification',
    REJECT_EXAM = 'rejectExamFeedbackNotification',
    PUBLISH_QUESTION = 'publishQuestionNotification',
    APPROVE_QUESTION = 'approveQuestionNotification',
    REJECT_QUESTION = 'rejectQuestionNotification',
    PUBLISH_QUIZ_QUESTION = 'publishQuizQuestionNotification',
    APPROVE_QUIZ_QUESTION = 'approveQuizQuestionNotification',
    REJECT_QUIZ_QUESTION = 'rejectQuizQuestionNotification',
    UNKNOWN = 'unknown',
}
